# Generated by Django 3.2.15 on 2022-11-13 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20221112_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadeBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('readNo', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(default=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('bookId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readEbook', to='online.ebook')),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
    ]
