# Generated by Django 3.2.15 on 2022-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytip',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
