# Generated by Django 3.2.15 on 2022-10-04 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdBy', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('placeOfPublication', models.CharField(blank=True, max_length=60, null=True)),
                ('yearOfPublication', models.CharField(blank=True, max_length=50, null=True)),
                ('coverPageImage', models.FileField(upload_to='coverPageImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(blank=True, max_length=20, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userId', models.CharField(blank=True, max_length=255, null=True)),
                ('issueDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('isPending', models.BooleanField(default=True)),
                ('isTaken', models.BooleanField(default=False)),
                ('isREturned', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('bookId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.book')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='book.category'),
        ),
    ]
