# Generated by Django 3.2.15 on 2022-10-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20221012_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestedbook',
            options={'ordering': ['-updatedAt']},
        ),
    ]
