# Generated by Django 3.2.15 on 2022-10-18 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_requestedbook_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaximumBookLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stuff', models.CharField(blank=True, max_length=1, null=True)),
                ('student', models.CharField(blank=True, max_length=1, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
