# Generated by Django 3.2.15 on 2022-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_maximumbooklimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='maximumbooklimit',
            name='days',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
