# Generated by Django 3.2.15 on 2022-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_maximumbooklimit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
